---
#
# Playbook to install the ELK stack + Beats
#

- hosts: all
  gather_facts: no
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
    - shell: apt-get upgrade; apt-get update
    - name: install nginx
      apt: 
       name: nginx
       state: latest
    - name: start nginx
      service:
          name: nginx
          state: started
 # roles:
  #- { role: java }
  #- { role: elasticsearch }
  #- { role: kibana }
  #- { role: metricbeat }

