---
#
# Playbook to install the ELK stack + Beats
#

- hosts: all
  gather_facts: no
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
    - name: start nginx
      service:
          name: nginx
          state: started
 # roles:
  #- { role: java }
  #- { role: elasticsearch }
  #- { role: kibana }
  #- { role: metricbeat }

